version: '2'

services:
    nginx:
      image: datosgobar/portal-base-nginx:release-0.10.1
      ports:
        - 80:80
      depends_on:
        - portal
    portal:
        build: 
          context: .
          args:
            - PORTAL_VERSION
        ports:
          - 8800:8800
          - 8080:8080
        depends_on:
           - db
           - solr
           - redis
           - postfix
        volumes:
          - $PWD:/dev-app
    db:
      image: postgres:9.5
      environment:
        - POSTGRES_USER=ckan
        - POSTGRES_PASSWORD=ckan
        - POSTGRES_DB=ckan
    redis:
      image: redis:3.2.7-alpine
    solr:
      image: datosgobar/portal-base-solr:release-0.9.0
    postfix:
      image: catatnight/postfix
      environment:
        - maildomain=localhost
        - smtp_user=portal:portal
      expose:
        - "25"
