site_name: Portal Andino
pages:
  - Home: 'index.md'
  - Instalación: 'setup/install.md'
  - Actualización: 'setup/update.md'
  - Migracion: 'setup/migration.md'
  - Uso: 'setup/usage.md'
  - Recomendaciones para Sysadmins: 'setup/recommendations.md'
  - Desarrollo:
    - Docker: 'development/docker.md'
    - Tests: 'development/tests.md'

