site_name: Portal Andino
pages:
  - Inicio: 'index.md'
  - Comienzo rápido: 'quickstart.md'
  - Manual de uso: 'usage.md'
  - Desarrollo:
    - Instalación: 'developers/install.md'
    - Actualización: 'developers/update.md'
    - Migracion: 'developers/migration.md'
    - Mantenimiento: 'developers/maintenance.md'
    - Configuración HTTPS: 'developers/https.md'
    - Generación de imágenes Docker: 'developers/docker.md'
    - Tests: 'developers/tests.md'

