site_name: Portal Andino
pages:
  - Home: 'index.md'
  - Instalacion: 'setup/install.md'
  - Migracion: 'setup/migration.md'
  - Uso: 'setup/usage.md'
  - Desarrollo:
    - Docker: 'development/docker.md'
    - Tests: 'development/tests.md'
